# Generated by Django 4.0.4 on 2022-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
